type ContentRow = {key:string;value:string;type:string};
// Exact retired copy only. Never reset an editor's unrelated changes.
const retired:Record<string,string[]> = {
	"home.team.text":["This section is prepared for verified ALS team information. Placeholder profiles should be replaced only with confirmed member details."],
	"blog.submissionGuidelines":["Submission Guidelines"],
	"blog.documentComingSoon":["Document coming soon after official confirmation."],
	"competitions.noEventsText":["Add upcoming debate or moot court dates here only after ALS confirms them through its official channels."],
	"competitions.noEventsTitle":["No verified upcoming events listed yet"],
	"competitions.documentComingSoon":["Document coming soon"],
	"competitions.draftExampleEyebrow":["Legislative drafting"],
	"competitions.draftExampleTitle":["Best Legislative Draft Example"],
	"competitions.draftExampleText":["This space is prepared for a strong sample law draft once ALS provides the official document."],
	"competitions.viewExample":["View Example"],
	"competitions.verificationNoteLabel":["Verification note: "],
	"contact.linkPending":["Link pending"],
	"gallery.intro":["A living record of debates, moot courts, talks, and community moments from ADA Law Society."],
	"gallery.image.1":["/images/placeholders/gallery-1.jpg"],
	"gallery.image.2":["/images/placeholders/gallery-2.jpg"],
	"gallery.image.3":["/images/placeholders/gallery-3.jpg"],
	"gallery.image.4":["/images/placeholders/gallery-4.jpg"],
	"gallery.image.5":["/images/placeholders/event-1.jpg"],
	"gallery.image.6":["/images/placeholders/event-2.jpg"],
	"gallery.image.7":["/images/placeholders/event-3.jpg"],
	"gallery.image.8":["/images/placeholders/event-4.jpg"],
	"gallery.image.9":["/images/placeholders/event-5.jpg"],
	"gallery.image.10":["/images/placeholders/event-6.jpg"],
	"gallery.caption.1":["Moot Court Finals Night"],
	"gallery.caption.2":["Legal Talks Series"],
	"gallery.caption.3":["Debate Championship"],
	"gallery.caption.4":["Academic Excursion"],
	"gallery.caption.5":["Orientation Week"],
	"gallery.caption.6":["Blog Editorial Meeting"],
	"gallery.caption.7":["Guest Lecture"],
	"gallery.caption.8":["Team Building Retreat"],
	"gallery.caption.9":["Networking Night"],
	"gallery.caption.10":["Graduation Ceremony"],
};
export function publicOverrides(rows:ContentRow[]) {
 return Object.fromEntries(rows.filter(row=>!retired[row.key]?.includes(row.value)).map(({key,value,type})=>[key,{value,type}]));
}
