-- Inline CMS content store for superadmin page editing
-- Run this manually in the Supabase SQL editor (not linked to local preview yet).

create table if not exists public.content (
  key text primary key,
  value text not null default '',
  type text not null default 'text',
  updated_at timestamp with time zone not null default now(),
  updated_by text
);

alter table public.content disable row level security;

insert into public.content (key, value, type)
values
  ('hero.title', 'Your Gateway to the Legal World', 'text'),
  ('hero.subtitle', 'Founded in September 2019, ADA Law Society is the first and main student organization for law students at ADA University.', 'text'),
  ('hero.image', '/images/hero-courtroom.jpg', 'image'),

  ('home.about.title', 'Where legal curiosity becomes legal confidence', 'text'),
  ('home.about.text', 'ALS brings together students interested in advocacy, legal research, debates, moot courts, legal writing, and professional development. Its mission is to create a rigorous, collaborative, and practical legal environment beyond the classroom.', 'text'),
  ('home.about.image', '/images/placeholders/about-als.jpg', 'image'),
  ('home.students.title', 'By Students, For Future Lawyers', 'text'),
  ('home.students.text', 'ALS is built around the idea that legal education becomes stronger when students create serious spaces for discussion, writing, advocacy, and professional growth.', 'text'),

  ('about.eyebrow', 'About ADA Law Society', 'text'),
  ('about.title', 'A professional home for legal ambition at ADA University', 'text'),
  ('about.body', 'Established in September 2019, ADA Law Society is the first and main student organization for law students at ADA University.', 'text'),
  ('about.image', '/images/placeholders/about-page.jpg', 'image'),
  ('about.story.eyebrow', 'Our Story', 'text'),
  ('about.story.title', 'Founded in 2019 to make legal education more active, practical, and collaborative', 'text'),
  ('about.story.text', 'ALS gives law students a serious student-led platform for legal writing, advocacy, debate, research, professional development, and dialogue with the wider university community.', 'text'),
  ('about.mission', 'To organize extra-curricular legal activities that extend students'' knowledge, improve student life on campus, and create a rigorous legal environment beyond the classroom.', 'text'),
  ('about.vision', 'To be a credible student-led legal community where advocacy, legal writing, debate, research, and professional development grow together.', 'text'),
  ('about.history', 'ALS was founded in September 2019 to bring law students together around lectures, talks, legal discussions, academic excursions, moot court activities, and a more productive student life on campus.', 'text'),
  ('about.cta.text', 'Contact ALS about membership, collaborations, legal writing, academic events, debate, moot court training, or professional development opportunities.', 'text'),

  ('contact.title', 'Connect with ADA Law Society', 'text'),
  ('contact.intro', 'Send a message about partnerships, membership, blog submissions, competitions, or upcoming legal events.', 'text'),
  ('contact.email', 'lawsociety@ada.edu.az', 'text'),
  ('contact.location', 'ADA University, Baku, Azerbaijan', 'text'),

  ('news.title', 'Newsroom', 'text'),
  ('news.intro', 'Verified public ALS updates, cooperation announcements, and society news.', 'text'),
  ('blog.title', 'Legal Insights Library', 'text'),
  ('blog.intro', 'Student legal writing with summaries, citations, and editorial review.', 'text'),

  ('team.archive.title', 'ADA Law Society Team Archive', 'text'),
  ('team.archive.intro', 'A public record of ALS leadership periods, early board members, and recent student-led committees.', 'text'),
  ('team.archive.early.eyebrow', 'Early Leadership Records', 'text'),
  ('team.archive.early.title', 'ALS Team 2019-2023', 'text'),
  ('team.archive.early.text', 'Names and roles below are listed exactly from the provided ALS team records.', 'text'),
  ('team.archive.recent.eyebrow', 'Recent Leadership Gallery', 'text'),
  ('team.archive.recent.title', 'Browse Recent Team Years', 'text')
on conflict (key) do nothing;

-- Pass 2: full site-wide coverage (every remaining visible string except the header/nav)
insert into public.content (key, value, type)
values
  -- Footer
  ('footer.tagline', 'Your Gateway to the Legal World', 'text'),
  ('footer.description', 'Your Gateway to the Legal World. ADA Law Society is the first and main student organization for law students at ADA University, founded in September 2019.', 'text'),
  ('footer.quickLinks', 'Quick links', 'text'),
  ('footer.policies', 'Policies', 'text'),
  ('footer.email', 'lawsociety@ada.edu.az', 'text'),
  ('footer.instagram', '@adalawsociety', 'text'),
  ('footer.location', 'ADA University, Baku, Azerbaijan', 'text'),
  ('footer.copyright', 'All rights reserved.', 'text'),
  ('footer.established', 'Established September 2019', 'text'),
  ('footer.link.about', 'About', 'text'),
  ('footer.link.news', 'News', 'text'),
  ('footer.link.blog', 'Blog', 'text'),
  ('footer.link.team', 'ALS Team', 'text'),
  ('footer.link.competitions', 'Competitions', 'text'),
  ('footer.link.contact', 'Contact', 'text'),
  ('footer.link.blogPolicy', 'Blog Policy', 'text'),
  ('footer.link.privacyPolicy', 'Privacy Policy', 'text'),
  ('footer.link.terms', 'Terms', 'text'),

  -- Home page (remaining sections)
  ('home.about.badge.title', 'Established September 2019', 'text'),
  ('home.about.badge.text', 'Student-led legal community', 'text'),
  ('home.feature.classroom.title', 'Beyond the classroom', 'text'),
  ('home.feature.classroom.text', 'Extra-curricular legal work helps students apply legal concepts to practical formats.', 'text'),
  ('home.feature.rigorous.title', 'Rigorous but collaborative', 'text'),
  ('home.feature.rigorous.text', 'The society encourages disciplined preparation while keeping participation peer-led and welcoming.', 'text'),
  ('home.feature.connected.title', 'Connected to ADA''s learning culture', 'text'),
  ('home.feature.connected.text', 'ALS aligns with ADA''s emphasis on applied knowledge, teamwork, debate, and real-world problem solving.', 'text'),
  ('home.feature.curiosity.title', 'Open to legal curiosity', 'text'),
  ('home.feature.curiosity.text', 'Events can interest law students and students from other majors who want to understand legal issues.', 'text'),
  ('home.activities.eyebrow', 'Explore', 'text'),
  ('home.activities.title', 'What We Do', 'text'),
  ('home.activities.text', 'From legal talks to courtroom simulation, every format is designed to support academic rigor, public reasoning, professional growth, and real-world problem solving.', 'text'),
  ('home.activities.legalTalks.title', 'Legal Talks', 'text'),
  ('home.activities.legalTalks.description', 'Practitioner and academic conversations that connect legal theory to real professional questions.', 'text'),
  ('home.activities.mootCourt.title', 'Moot Court Training', 'text'),
  ('home.activities.mootCourt.description', 'Memorial writing, oral advocacy, legal research, teamwork, and simulated court rounds.', 'text'),
  ('home.activities.debates.title', 'Debates', 'text'),
  ('home.activities.debates.description', 'Structured argumentation, legal reasoning, public speaking, and civic discussion.', 'text'),
  ('home.activities.blog.title', 'Blog & Legal Research', 'text'),
  ('home.activities.blog.description', 'Student legal writing with summaries, citations, editorial review, and research discipline.', 'text'),
  ('home.activities.excursions.title', 'Academic Excursions', 'text'),
  ('home.activities.excursions.description', 'Institutional visits that make legal procedure and public service visible.', 'text'),
  ('home.activities.networking.title', 'Professional Networking', 'text'),
  ('home.activities.networking.description', 'Peer, faculty, alumni, and practitioner connections for future-facing legal careers.', 'text'),
  ('home.competitions.eyebrow', 'Competitions', 'text'),
  ('home.competitions.title', 'Competitions that sharpen advocacy', 'text'),
  ('home.competitions.text', 'Debate and moot court programs give students the discipline, structure, and confidence to argue with evidence and integrity.', 'text'),
  ('home.competitions.cta', 'Explore', 'text'),
  ('home.team.title', 'ALS team directory', 'text'),
  ('home.team.text', 'This section is prepared for verified ALS team information. Placeholder profiles should be replaced only with confirmed member details.', 'text'),
  ('home.team.cta', 'ALS Team', 'text'),
  ('home.moments.title', 'ALS moments', 'text'),
  ('home.moments.text', 'A living record of events, trainings, discussions, visits, and community work around ADA University.', 'text'),
  ('home.social.title', 'Stay close to the society', 'text'),
  ('home.social.text', 'Follow @adalawsociety for public updates, event announcements, blog calls, competition information, and student opportunities.', 'text'),
  ('home.featuredNews.title', 'Featured news', 'text'),
  ('home.featuredNews.text', 'Updates, announcements, collaborations, and student-led legal initiatives from ADA Law Society.', 'text'),
  ('home.featuredNews.cta', 'News', 'text'),
  ('home.featuredBlog.title', 'Featured articles', 'text'),
  ('home.featuredBlog.text', 'Student-written legal analysis, advocacy reflections, research notes, and debate-driven ideas.', 'text'),
  ('home.featuredBlog.cta', 'Blog', 'text'),
  ('home.marquee.0', 'Moot Court', 'text'),
  ('home.marquee.1', 'Legal Writing', 'text'),
  ('home.marquee.2', 'Debate', 'text'),
  ('home.marquee.3', 'Advocacy', 'text'),
  ('home.marquee.4', 'Legal Research', 'text'),
  ('home.marquee.5', 'Student Leadership', 'text'),
  ('home.marquee.6', 'Academic Excellence', 'text'),
  ('home.marquee.7', 'Your Gateway to the Legal World', 'text'),
  ('home.marquee.8', 'ADA Law Society', 'text'),

  -- Contact page (remaining)
  ('contact.eyebrow', 'Contact', 'text'),
  ('contact.emailLabel', 'Email', 'text'),
  ('contact.locationLabel', 'Location', 'text'),
  ('contact.socialLabel', 'Social media', 'text'),
  ('contact.linkPending', 'Link pending', 'text'),
  ('contact.form.name', 'Name', 'text'),
  ('contact.form.email', 'Email', 'text'),
  ('contact.form.subject', 'Subject', 'text'),
  ('contact.form.message', 'Message', 'text'),
  ('contact.form.send', 'Send message', 'text'),
  ('contact.form.sentMessage', 'Your message is ready for a future backend connection.', 'text'),

  -- News listing / detail / card
  ('news.eyebrow', 'ADA Law Society Updates', 'text'),
  ('news.createButton', 'Create News', 'text'),
  ('news.filterLabel', 'Filter updates', 'text'),
  ('news.filterAll', 'All', 'text'),
  ('news.feedLabel', 'News feed', 'text'),
  ('news.feedCaption', 'Verified public ALS updates currently listed.', 'text'),
  ('news.feedFilteredCaption', 'Matching public updates in the current view.', 'text'),
  ('news.singleMatchTitle', 'Only one update matches this view.', 'text'),
  ('news.singleMatchText', 'Adjust the filters or search to explore more ALS updates.', 'text'),
  ('news.noResultsTitle', 'No results found.', 'text'),
  ('news.noResultsText', 'Try another category or clear the search field to return to the full newsroom.', 'text'),
  ('news.resetButton', 'Reset newsroom', 'text'),
  ('news.card.featuredLabel', 'Featured update', 'text'),
  ('news.card.readFullUpdate', 'Read full update', 'text'),
  ('news.card.readMore', 'Read more', 'text'),
  ('news.card.placeholderBadge', 'ALS', 'text'),
  ('news.card.placeholderTitle', 'ADA Law Society Update', 'text'),
  ('news.detail.backLink', 'Back to news', 'text'),
  ('news.detail.sourceLabel', 'Public source: ', 'text'),
  ('news.detail.sourceLinkText', 'ADA Law Society public news page', 'text'),
  ('news.detail.relatedTitle', 'Related news', 'text'),

  -- Blog listing / detail / card / comments
  ('blog.eyebrow', 'ADA Law Society Blog', 'text'),
  ('blog.writeButton', 'Write Article', 'text'),
  ('blog.editorDesk', 'Editor''s Desk', 'text'),
  ('blog.writingForClarity', 'Writing for legal clarity', 'text'),
  ('blog.standards.0', 'Abstract required', 'text'),
  ('blog.standards.1', 'Clear citation practice', 'text'),
  ('blog.standards.2', 'Original writing / no plagiarism', 'text'),
  ('blog.standards.3', 'Respectful academic tone', 'text'),
  ('blog.standards.4', 'Editorial review before publication', 'text'),
  ('blog.standards.5', 'Follow assigned word count', 'text'),
  ('blog.authorDocumentsTitle', 'Author Documents', 'text'),
  ('blog.authorDocumentsText', 'Use these references before drafting or submitting ALS blog content.', 'text'),
  ('blog.blogPolicy', 'Blog Policy', 'text'),
  ('blog.blogPolicyText', 'Review editorial expectations and publication rules.', 'text'),
  ('blog.submissionGuidelines', 'Submission Guidelines', 'text'),
  ('blog.documentComingSoon', 'Document coming soon after official confirmation.', 'text'),
  ('blog.browseInsights', 'Browse insights', 'text'),
  ('blog.filterAll', 'All', 'text'),
  ('blog.searchBlogs', 'Search blogs', 'text'),
  ('blog.blogIndex', 'Blog', 'text'),
  ('blog.latestBlogs', 'Latest Blogs', 'text'),
  ('blog.singleBlog', 'blog', 'text'),
  ('blog.blogs', 'blogs', 'text'),
  ('blog.inView', 'in view', 'text'),
  ('blog.onlyOneMatchTitle', 'Only one blog matches this library view.', 'text'),
  ('blog.onlyOneMatchText', 'Adjust search, category, or author filters to browse more writing.', 'text'),
  ('blog.noResultsTitle', 'No results found.', 'text'),
  ('blog.noResultsText', 'Try another filter or clear the search field to return to the full insights library.', 'text'),
  ('blog.resetLibrary', 'Reset library', 'text'),
  ('blog.card.featuredLabel', 'Featured Blog', 'text'),
  ('blog.card.readBlog', 'Read blog', 'text'),
  ('blog.card.readMore', 'Read more', 'text'),
  ('blog.card.abstractLabel', 'Abstract', 'text'),
  ('blog.card.citationsLabel', 'Citations', 'text'),
  ('blog.detail.backLink', 'Back to blog', 'text'),
  ('blog.detail.summaryLabel', 'Author summary', 'text'),
  ('blog.detail.citationsLabel', 'Citations', 'text'),
  ('blog.detail.sourceLinkText', 'Source', 'text'),
  ('blog.detail.relatedTitle', 'Related articles', 'text'),
  ('blog.comments.eyebrow', 'Discussion', 'text'),
  ('blog.comments.singular', 'comment', 'text'),
  ('blog.comments.plural', 'comments', 'text'),
  ('blog.comments.submitButton', 'Submit', 'text'),
  ('blog.comments.emptyState', 'No comments yet. Start the discussion.', 'text'),
  ('blog.comments.replyButton', 'Reply', 'text'),

  -- Competitions
  ('competitions.eyebrow', 'Competitions', 'text'),
  ('competitions.debate.title', 'Debate at ADA Law Society', 'text'),
  ('competitions.debate.intro', 'ALS debates are a platform for argumentation, legal reasoning, public speaking, and civic discussion.', 'text'),
  ('competitions.debate.image', '/images/placeholders/debate.jpg', 'image'),
  ('competitions.moot-court.title', 'Moot Court at ADA Law Society', 'text'),
  ('competitions.moot-court.intro', 'Moot courts are simulated court proceedings where students practice memorial writing, oral advocacy, legal research, teamwork, and disciplined legal analysis.', 'text'),
  ('competitions.moot-court.image', '/images/placeholders/moot-court.jpg', 'image'),
  ('competitions.upcoming', 'Upcoming', 'text'),
  ('competitions.noEventsTitle', 'No verified upcoming events listed yet', 'text'),
  ('competitions.noEventsText', 'Add upcoming debate or moot court dates here only after ALS confirms them through its official channels.', 'text'),
  ('competitions.highlights', 'Past highlights', 'text'),
  ('competitions.format', 'Rules and format', 'text'),
  ('competitions.rulesIntro', 'Before participating, students can review the official format, scoring principles, and participation rules.', 'text'),
  ('competitions.viewRules', 'View Rules', 'text'),
  ('competitions.documentComingSoon', 'Document coming soon', 'text'),
  ('competitions.draftExampleEyebrow', 'Legislative drafting', 'text'),
  ('competitions.draftExampleTitle', 'Best Legislative Draft Example', 'text'),
  ('competitions.draftExampleText', 'This space is prepared for a strong sample law draft once ALS provides the official document.', 'text'),
  ('competitions.viewExample', 'View Example', 'text'),
  ('competitions.verificationNoteLabel', 'Verification note: ', 'text'),

  -- Team archive / year
  ('team.archive.badge', 'ALS Team', 'text'),
  ('team.year.leadershipArchive', 'ALS Leadership Archive', 'text'),
  ('team.year.board.title', 'Board', 'text'),
  ('team.year.board.description', 'The core ALS leadership team responsible for coordination, administration, finance, events, marketing, and editorial direction.', 'text'),
  ('team.year.eventCommittee.title', 'Event Committee', 'text'),
  ('team.year.eventCommittee.description', 'Students supporting ALS programming, logistics, debate activity, moot court preparation, and event coordination.', 'text'),
  ('team.year.marketingCommittee.title', 'Marketing Committee', 'text'),
  ('team.year.marketingCommittee.description', 'Students shaping ALS communication through content, design, interviews, video, and web presence.', 'text'),
  ('team.year.blogCommittee.title', 'Blog Committee', 'text'),
  ('team.year.blogCommittee.description', 'Students supporting ALS legal writing through editing, review, and editorial coordination.', 'text')
on conflict (key) do nothing;
